# run: conda env create --file environment.yml
name: hmo_identifier
channels:
  - conda-forge
  - defaults
dependencies:
  - folium=0.10.1
  - shapely=1.7.0
  - psycopg2=2.8.4
  - pandas=0.25.3
  - python-dotenv=0.10.5
  - requests=2.22.0
  - jupyter
  - matplotlib
  - beautifulsoup4
  - descartes
  - xlrd
  - scikit-learn
  - black
  - sphinx=1.8.4
  - m2r
  - sphinx_rtd_theme
  - nb_conda_kernels
  - netcdf4
  - lxml
  - h5py
  - contextily
  - nltk
  - ipykernel
