# run: conda env create --file environment.yml
name: hmo_test
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - shapely=1.7.0
  - psycopg2=2.8.4
  - pandas=0.25.3
  - python-dotenv=0.10.5
  - requests=2.22.0
  - jupyter
  - matplotlib
  - beautifulsoup4
  - scikit-learn
  - pip
  - pip:
    - recordlinkage


